backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("vehicle_management.urls")),
    path('admin/', admin.site.urls),
]

backend/vehicle_management/urls.py
from django.urls import path

from . import views

# Define a namespace to use url namespace:name
app_name = "vehicle_management"

urlpatterns = [
    path("", views.IndexView.as_view(), name="car-index"),
    path("cars/<int:pk>", views.CarDetailsView.as_view(), name="car-details"),
    path("cars/create", views.CarCreateView.as_view(), name="car-create"),
    path("cars/delete/<int:pk>", views.car_delete, name="car-delete"),
    path("cars/update/<int:pk>", views.CarUpdateView.as_view(), name="car-update"),
]

backend/vehicle_management/models.py
from django.db import models


class Car(models.Model):
    title = models.CharField(max_length=100)
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.PositiveIntegerField()
    mileage = models.PositiveIntegerField()
    vin = models.CharField(max_length=17, unique=True)

    def __repr__(self):
        return f"Car(title=\"{self.title}\")"

    def __str__(self):
        return self.title


class MaintenanceTask(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=1000)
    mileage_threshold = models.PositiveIntegerField()
    car = models.ForeignKey(Car, on_delete=models.CASCADE)


class MaintenanceEntry(models.Model):
    maintenance_date = models.DateField()
    elapsed_mileage = models.PositiveIntegerField()
    notes = models.TextField(max_length=1000)
    task = models.ForeignKey(MaintenanceTask, on_delete=models.CASCADE)

backend/vehicle_management/views.py
from django import forms
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView

from vehicle_management.models import Car


class IndexView(generic.ListView):
    template_name = "cars/index.html"
    context_object_name = "cars"

    def get_queryset(self):
        return Car.objects.all()


class CarDetailsView(generic.DetailView):
    template_name = "cars/details.html"
    context_object_name = "car"
    model = Car


class CarForm(forms.ModelForm):
    class Meta:
        model = Car
        fields = [
            "title",
            "make",
            "model",
            "year",
            "mileage",
            "vin",
        ]
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "make": forms.TextInput(attrs={"class": "form-control"}),
            "model": forms.TextInput(attrs={"class": "form-control"}),
            "year": forms.NumberInput(attrs={"class": "form-control"}),
            "mileage": forms.NumberInput(attrs={"class": "form-control"}),
            "vin": forms.TextInput(attrs={"class": "form-control"}),
        }


class CarCreateView(CreateView):
    model = Car
    form_class = CarForm
    template_name = "cars/create.html"

    def get_success_url(self):
        return reverse_lazy("vehicle_management:car-details", kwargs={"pk": self.object.pk})


class CarUpdateView(UpdateView):
    model = Car
    form_class = CarForm
    template_name = "cars/create.html"

    def get_success_url(self):
        return reverse_lazy("vehicle_management:car-details", kwargs={"pk": self.object.pk})


def car_delete(request, pk):
    if request.method == "DELETE":
        car = get_object_or_404(Car, pk=pk)
        car.delete()

        return JsonResponse({"message": "Car deleted."})
    else:
        return JsonResponse({"message": "Method not allowed."}, status=405)

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>GetHub</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
</head>
<body>
<script type="text/javascript">
    const getCookie = name => {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    };

    const httpRequest = (url, callback, failCallback = null, method = "GET") => {
        const request = new XMLHttpRequest();
        request.onreadystatechange = () => {
            if (request.readyState === 4 && request.status === 200) callback(request);
            if (request.readyState === 4 && request.status !== 200 && failCallback !== null) {
                failCallback(request);
            }
        };
        request.open(method, url, true);
        request.setRequestHeader('X-CSRFToken', getCookie("csrftoken"));
        request.send();
    };
</script>

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'vehicle_management:car-index' %}">GetHub</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a href="{% url 'vehicle_management:car-create' %}" class="nav-link" aria-current="page">
                        Create a car
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

backend/vehicle_management/templates/cars/create.html
{% extends "base.html" %}

{% block content %}
    <form action="{% url 'vehicle_management:car-create' %}" method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-3">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <p class="help" id="{{ field.auto_id }}_helptext">
                        {{ field.help_text | safe }}
                    </p>
                {% endif %}
            </div>
        {% endfor %}
        <button class="btn btn-primary" type="submit">OK</button>
    </form>
{% endblock %}

backend/vehicle_management/templates/cars/details.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ car.title }}</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col"></th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th scope="row">Make</th>
            <td>{{ car.make }}</td>
        </tr>
        <tr>
            <th scope="row">Model</th>
            <td>{{ car.model }}</td>
        </tr>
        <tr>
            <th scope="row">Year</th>
            <td>{{ car.year }}</td>
        </tr>
        <tr>
            <th scope="row">Mileage</th>
            <td>{{ car.mileage }}</td>
        </tr>
        <tr>
            <th scope="row">VIN</th>
            <td>{{ car.vin }}</td>
        </tr>
        </tbody>
    </table>
    <div class="row">
        <div class="col-md-8">
            <button class="btn btn-primary" id="delete-button">Delete</button>
            <a href="{% url 'vehicle_management:car-update' pk=car.id %}" class="btn btn-primary">Edit</a>
        </div>
    </div>
    <script type="text/javascript">
        document.getElementById("delete-button").addEventListener("click", e => {
            e.preventDefault();
            const deletionUrl = "{% url "vehicle_management:car-delete" pk=car.id %}";

            const successCallback = successfulResult => {
                const responseText = successfulResult.response;
                const jsonContent = JSON.parse(responseText);
                if (jsonContent.message === "Car deleted.") {
                    window.location.href = "{% url 'vehicle_management:car-index' %}";
                }
            };

            const failCallback = failedResult => {
                const statusCode = failedResult.status;
                alert(`Deletion failed with code ${statusCode}. See console for details.`);
                console.error(failedResult);
            };

            httpRequest(deletionUrl, successCallback, failCallback, "DELETE");
        });
    </script>
{% endblock %}

backend/vehicle_management/templates/cars/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Cars list</h1>
    {% if cars %}
        <div class="col-md-3">
            <ul class="list-group">
                {% for car in cars %}
                    <li class="list-group-item">
                        <a href="{% url 'vehicle_management:car-details' car.id %}">{{ car.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    {% else %}
        No cars ):
    {% endif %}
{% endblock %}